---
title: "Prod - Levered Vigilant Asset Allocation"
author: "Keith Berry"
date: "January 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(kableExtra)


con = gzcon(url('https://github.com/systematicinvestor/SIT/raw/master/sit.gz', 'rb'))
source(con)
close(con)

load.packages('quantmod')   
```

```{r load-data, echo=FALSE}

models = list()

data <- readRDS("./data/raw-prices.RData")

bt.prep(data, align='remove.na')

prices = data$prices 

ret = bt.apply.matrix(prices, ROC, type='discrete')
abs.ret = abs(ret) * 100
abs.ret.average = bt.apply.matrix(abs.ret, SMA, 30)

plot(abs.ret.average[,spl("VOO,VEA,VWO")])

period.ends = endpoints(prices, 'months')
period.ends = period.ends[period.ends > 0]		
period.ends = c(1, period.ends)

monthly.prices = prices[period.ends,]

m1.ret = monthly.prices/mlag(monthly.prices,1)-1
m3.ret = monthly.prices/mlag(monthly.prices,3)-1
m6.ret = monthly.prices/mlag(monthly.prices,6)-1
m12.ret = monthly.prices/mlag(monthly.prices,12)-1

f13612w = ((12*m1.ret+4*m3.ret+2*m6.ret+1*m12.ret)/4)*100

m1.ret.daily = prices/mlag(prices,21)-1
m3.ret.daily = prices/mlag(prices,63)-1
m6.ret.daily = prices/mlag(prices,126)-1
m12.ret.daily = prices/mlag(prices,252)-1

f13612w.daily = ((12*m1.ret.daily+4*m3.ret.daily+2*m6.ret.daily+1*m12.ret.daily)/4)*100

risky = spl("VOO,VEA,VWO,BND")
safe = spl("SHY,IEF,LQD")

top.risky = ntop(f13612w[,risky],1) 
risk.on = rowSums(f13612w[,risky] < 0)==0

#leverage = 1/abs.ret.average
#leverage = 2 
#leverage$SHY = 1

#risky.positions = top.risky * risk.on * leverage[,risky]
risky.positions = top.risky * risk.on * 2

top.safe = ntop(f13612w[,safe],1)
risk.off = rowSums(f13612w[,risky] < 0)>0

#safe.positions = top.safe * risk.off * leverage[,safe]
safe.positions = top.safe * risk.off * 2

#data$prices = data$prices[period.ends,]
data$weight = data$prices[period.ends,]
#data$weight[] = 0

positions = cbind(risky.positions,safe.positions)
positions$TLT = 0

data$weight = prices
data$weight[] = NA
data$weight[period.ends,]= positions[,colnames(data$weight)]
models$vaa.g4.t1.b1.l1 = bt.run(data, type='weight', trade.summary=T)

currentModel = models$vaa.g4.t1.b1.l1
currentModel$equity=currentModel$equity["1997-04-30/"]
model.detail = bt.detail.summary(currentModel)
twelve.ret = ROC(currentModel$equity,12,type="discrete")
model.detail$System$Roll.TwelveM = (sum(twelve.ret > 0,na.rm=TRUE)/(sum(twelve.ret > 0,na.rm=TRUE)+sum(twelve.ret < 0,na.rm=TRUE)))*100

kable(list2matrix(model.detail)) %>% kable_styling()
plotbt.monthly.table(currentModel$equity)
plot(currentModel$equity)
plot(compute.drawdown(currentModel$equity)*100)
kable(tail(f13612w,13)) %>% kable_styling()
kable(list2matrix(tail(currentModel$trade.summary$trades,13))) %>% kable_styling()
kable(list2matrix(model.detail)) %>% kable_styling()
# Need to align the pricing columns
```

With varying leverage

```{r, echo=FALSE}

top.risky = ntop(f13612w[,risky],1) 
risk.on = rowSums(f13612w[,risky] < 0)==0

leverage = 1/abs.ret.average
#leverage = 2 
#leverage$SHY = 1

risky.positions = top.risky * risk.on * leverage[,risky]
#risky.positions = top.risky * risk.on * 2

top.safe = ntop(f13612w[,safe],1)
risk.off = rowSums(f13612w[,risky] < 0)>0

safe.positions = top.safe * risk.off * leverage[,safe]
#safe.positions = top.safe * risk.off * 2

#data$prices = data$prices[period.ends,]
data$weight = data$prices[period.ends,]
#data$weight[] = 0

positions = cbind(risky.positions,safe.positions)
positions$TLT = 0

data$weight = prices
data$weight[] = NA
data$weight[period.ends,]= positions[,colnames(data$weight)]
models$vaa.g4.t1.b1.lv = bt.run(data, type='weight', trade.summary=T)

currentModel = models$vaa.g4.t1.b1.lv
currentModel$equity=currentModel$equity["1997-04-30/"]
model.detail = bt.detail.summary(currentModel)
twelve.ret = ROC(currentModel$equity,12,type="discrete")
model.detail$System$Roll.TwelveM = (sum(twelve.ret > 0,na.rm=TRUE)/(sum(twelve.ret > 0,na.rm=TRUE)+sum(twelve.ret < 0,na.rm=TRUE)))*100

kable(list2matrix(model.detail)) %>% kable_styling()
plotbt.monthly.table(currentModel$equity)
plot(currentModel$equity)
plot(compute.drawdown(currentModel$equity)*100)
kable(tail(f13612w,13)) %>% kable_styling()
kable(list2matrix(tail(currentModel$trade.summary$trades,13))) %>% kable_styling()
kable(list2matrix(model.detail)) %>% kable_styling()
# Need to align the pricing columns
```

# Max leverage 3

```{r, echo=FALSE}

top.risky = ntop(f13612w[,risky],1) 
risk.on = rowSums(f13612w[,risky] < 0)==0

leverage = 1/abs.ret.average
leverage[] <- apply(leverage, 2,function(x) ifelse(x > 3, 3, x))
#leverage = 2 
#leverage$SHY = 1

risky.positions = top.risky * risk.on * leverage[,risky]
#risky.positions = top.risky * risk.on * 2

top.safe = ntop(f13612w[,safe],1)
risk.off = rowSums(f13612w[,risky] < 0)>0

safe.positions = top.safe * risk.off * leverage[,safe]
#safe.positions = top.safe * risk.off * 2

#data$prices = data$prices[period.ends,]
data$weight = data$prices[period.ends,]
#data$weight[] = 0

positions = cbind(risky.positions,safe.positions)
positions$TLT = 0

data$weight = prices
data$weight[] = NA
data$weight[period.ends,]= positions[,colnames(data$weight)]
models$vaa.g4.t1.b1.lv3 = bt.run(data, type='weight', trade.summary=T)

currentModel = models$vaa.g4.t1.b1.lv3
currentModel$equity=currentModel$equity["1997-04-30/"]
model.detail = bt.detail.summary(currentModel)
twelve.ret = ROC(currentModel$equity,12,type="discrete")
model.detail$System$Roll.TwelveM = (sum(twelve.ret > 0,na.rm=TRUE)/(sum(twelve.ret > 0,na.rm=TRUE)+sum(twelve.ret < 0,na.rm=TRUE)))*100

kable(list2matrix(model.detail)) %>% kable_styling()
plotbt.monthly.table(currentModel$equity)
plot(currentModel$equity)
plot(compute.drawdown(currentModel$equity)*100)
kable(tail(f13612w,13)) %>% kable_styling()
kable(list2matrix(tail(currentModel$trade.summary$trades,13))) %>% kable_styling()
kable(list2matrix(model.detail)) %>% kable_styling()
# Need to align the pricing columns
```

# Remove BND from investible

```{r, echo=FALSE}

risky = spl("VOO,VEA,VWO")
canary = spl("VOO,VEA,VWO,BND")

top.risky = ntop(f13612w[,risky],1) 
risk.on = rowSums(f13612w[,canary] < 0)==0

leverage = 1/abs.ret.average
leverage[] <- apply(leverage, 2,function(x) ifelse(x > 3, 3, x))
#leverage = 2 
#leverage$SHY = 1

risky.positions = top.risky * risk.on * leverage[,risky]
#risky.positions = top.risky * risk.on * 2

top.safe = ntop(f13612w[,safe],1)
risk.off = rowSums(f13612w[,canary] < 0)>0

safe.positions = top.safe * risk.off * leverage[,safe]
#safe.positions = top.safe * risk.off * 2

#data$prices = data$prices[period.ends,]
data$weight = data$prices[period.ends,]
#data$weight[] = 0

positions = data$prices
positions[] = 0
temp.positions = cbind(risky.positions,safe.positions)
positions[period.ends,colnames(temp.positions)] = temp.positions
#positions$TLT = 0

data$weight = prices
data$weight[] = NA
data$weight[period.ends,]= positions[period.ends,colnames(data$weight)]
models$vaa.g4.t1.b1.lv3.c = bt.run(data, type='weight', trade.summary=T)

currentModel = models$vaa.g4.t1.b1.lv3.c
currentModel$equity=currentModel$equity["1997-04-30/"]
model.detail = bt.detail.summary(currentModel)
twelve.ret = ROC(currentModel$equity,12,type="discrete")
model.detail$System$Roll.TwelveM = (sum(twelve.ret > 0,na.rm=TRUE)/(sum(twelve.ret > 0,na.rm=TRUE)+sum(twelve.ret < 0,na.rm=TRUE)))*100

kable(list2matrix(model.detail)) %>% kable_styling()
plotbt.monthly.table(currentModel$equity)
plot(currentModel$equity)
plot(compute.drawdown(currentModel$equity)*100)
kable(tail(f13612w,13)) %>% kable_styling()
kable(list2matrix(tail(currentModel$trade.summary$trades,13))) %>% kable_styling()
kable(list2matrix(model.detail)) %>% kable_styling()
# Need to align the pricing columns
```

# Latest version with leverage rounding

```{r, echo=FALSE}

risky = spl("VOO,VEA,VWO")
safe = spl("IEF,SHY,LQD")
canary = spl("VOO,VEA,VWO,BND")

top.risky = ntop(f13612w[,risky],1) 
risk.on = rowSums(f13612w[,canary] < 0)==0

leverage = 1/abs.ret.average
leverage[] <- apply(leverage, 2,function(x) ifelse(x > 3, 3, x))
leverage[] <- apply(leverage, 2, function(x) round(x/0.5)*0.5)
#leverage = 2 
#leverage$SHY = 1

risky.positions = top.risky * risk.on * leverage[,risky]
#risky.positions = top.risky * risk.on * 2

top.safe = ntop(f13612w[,safe],1)
risk.off = rowSums(f13612w[,canary] < 0)>0

safe.positions = top.safe * risk.off * leverage[,safe]
#safe.positions = top.safe * risk.off * 2

#data$prices = data$prices[period.ends,]
data$weight = data$prices[period.ends,]
#data$weight[] = 0

positions = data$prices
positions[] = 0
temp.positions = cbind(risky.positions,safe.positions)
positions[period.ends,colnames(temp.positions)] = temp.positions
#positions$TLT = 0

data$weight = prices
data$weight[] = NA
data$weight[period.ends,]= positions[period.ends,colnames(data$weight)]
models$vaa.g4.t1.b1.lv3.c.s = bt.run(data, type='weight', trade.summary=T)

currentModel = models$vaa.g4.t1.b1.lv3.c.s
currentModel$equity=currentModel$equity["1997-04-30/"]
model.detail = bt.detail.summary(currentModel)
twelve.ret = ROC(currentModel$equity,12,type="discrete")
model.detail$System$Roll.TwelveM = (sum(twelve.ret > 0,na.rm=TRUE)/(sum(twelve.ret > 0,na.rm=TRUE)+sum(twelve.ret < 0,na.rm=TRUE)))*100

kable(list2matrix(model.detail)) %>% kable_styling()
plotbt.monthly.table(currentModel$equity)
plot(currentModel$equity)
plot(compute.drawdown(currentModel$equity)*100)
kable(tail(f13612w,13)) %>% kable_styling()
kable(list2matrix(tail(currentModel$trade.summary$trades,13))) %>% kable_styling()
kable(list2matrix(model.detail)) %>% kable_styling()
# Need to align the pricing columns
```

# Using volatility as part of the measure 

```{r, echo=FALSE}

risky = spl("VOO,VEA,VWO")
safe = spl("IEF,SHY,LQD")
canary = spl("VOO,VEA,VWO,BND")

f13612w.vol = f13612w/abs.ret.average[period.ends]
top.risky = ntop(f13612w.vol[,risky],1) 
risk.on = rowSums(f13612w[,canary] < 0)==0

leverage = 1/abs.ret.average
leverage[] <- apply(leverage, 2,function(x) ifelse(x > 3, 3, x))
leverage[] <- apply(leverage, 2, function(x) round(x/0.5)*0.5)
#leverage = 2 
#leverage$SHY = 1

risky.positions = top.risky * risk.on * leverage[,risky]
#risky.positions = top.risky * risk.on * 2

top.safe = ntop(m6.ret[,safe],1)
risk.off = rowSums(f13612w[,canary] < 0)>0

safe.positions = top.safe * risk.off * leverage[,safe]
#safe.positions = top.safe * risk.off * 2

#data$prices = data$prices[period.ends,]
data$weight = data$prices[period.ends,]
#data$weight[] = 0

positions = data$prices
positions[] = 0
temp.positions = cbind(risky.positions,safe.positions)
positions[period.ends,colnames(temp.positions)] = temp.positions
#positions$TLT = 0

data$weight = prices
data$weight[] = NA
data$weight[period.ends,]= positions[period.ends,colnames(data$weight)]
models$vaa.g4.t1.b1.lv3.m6d = bt.run(data, type='weight', trade.summary=T)

currentModel = models$vaa.g4.t1.b1.lv3.m6d
currentModel$equity=currentModel$equity["1997-04-30/"]
model.detail = bt.detail.summary(currentModel)
twelve.ret = ROC(currentModel$equity,12,type="discrete")
model.detail$System$Roll.TwelveM = (sum(twelve.ret > 0,na.rm=TRUE)/(sum(twelve.ret > 0,na.rm=TRUE)+sum(twelve.ret < 0,na.rm=TRUE)))*100

kable(list2matrix(model.detail)) %>% kable_styling()
plotbt.monthly.table(currentModel$equity)
plot(currentModel$equity)
plot(compute.drawdown(currentModel$equity)*100)
kable(tail(f13612w,13)) %>% kable_styling()
kable(list2matrix(tail(currentModel$trade.summary$trades,13))) %>% kable_styling()
kable(list2matrix(model.detail)) %>% kable_styling()
# Need to align the pricing columns
```

# Compare all portfolios

```{r, echo=FALSE}

kable(plotbt.strategy.sidebyside(models, make.plot=F, return.table=T)) %>% kable_styling()
      
```